version: "3.8"

services:
  app:
    container_name: react-dev
    image: react-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000